---
# tasks file for install_supervisor
# Variable setup.   # 变量导入
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install supervisor
  include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Ensure supervisor service is running as configured.
  service:
    name: supervisor
    state: "{{ supervisor_service_state }}"
    enabled: "{{ supervisor_service_enabled }}"
  when: ansible_os_family == 'Debian'

